# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.9.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@7.3.5
    npm install
    ng build --prod
    sh ls
    echo $(Build.ArtifactStagingDirectory)
    echo $(Build.BuildId)
    echo $(System.DefaultWorkingDirectory)
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  displayName: 'Archive Files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact'
  inputs:
    artifactName: '$(Build.BuildId).zip'
    targetPath: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
    